global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: "consul-discovery"
  consul_sd_configs:
    - server: 'consul:8500'
  relabel_configs:
    - action: keep
      source_labels: [__meta_consul_service_id]
      regex: gpu_exporter
